on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-project-card@v2.0.1
        with:
          project-name: hjemmetest
          column-name: Todo
